project:
  type: website

website:
  title: "Bayesian Statistics 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: homework.qmd
        text: Homework
      - href: syllabus.qmd
        text: Syllabus

        
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

